kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"policy: disabled\ntemplate: |-\n  initContainers:\n  - name: istio-init\n    image: docker.io/istio/proxy_init:0.5.0\n    args:\n    - \"-p\"\n    - {{ .MeshConfig.ProxyListenPort }}\n    - \"-u\"\n    - 1337\n    - \"-i\"\n    - 10.194.0.0/15,10.192.0.0/20\n    imagePullPolicy: IfNotPresent\n    securityContext:\n      capabilities:\n        add:\n        - NET_ADMIN\n      privileged: true\n    restartPolicy: Always\n  containers:\n  - name: istio-proxy\n    image: docker.io/istio/proxy:0.5.0\n    args:\n    - proxy\n    - sidecar\n    - --configPath\n    - {{ .ProxyConfig.ConfigPath }}\n    - --binaryPath\n    - {{ .ProxyConfig.BinaryPath }}\n    - --serviceCluster\n    {{ if ne \"\" (index .ObjectMeta.Labels \"app\") -}}\n    - {{ index .ObjectMeta.Labels \"app\" }}\n    {{ else -}}\n    - \"istio-proxy\"\n    {{ end -}}\n    - --drainDuration\n    - 2s\n    - --parentShutdownDuration\n    - 3s\n    - --discoveryAddress\n    - {{ .ProxyConfig.DiscoveryAddress }}\n    - --discoveryRefreshDelay\n    - 1s\n    - --zipkinAddress\n    - {{ .ProxyConfig.ZipkinAddress }}\n    - --connectTimeout\n    - 1s\n    - --statsdUdpAddress\n    - {{ .ProxyConfig.StatsdUdpAddress }}\n    - --proxyAdminPort\n    - {{ .ProxyConfig.ProxyAdminPort }}\n    - --controlPlaneAuthPolicy\n    - {{ .ProxyConfig.ControlPlaneAuthPolicy }}\n    env:\n    - name: POD_NAME\n      valueFrom:\n        fieldRef:\n          fieldPath: metadata.name\n    - name: POD_NAMESPACE\n      valueFrom:\n        fieldRef:\n          fieldPath: metadata.namespace\n    - name: INSTANCE_IP\n      valueFrom:\n        fieldRef:\n          fieldPath: status.podIP\n    imagePullPolicy: IfNotPresent\n    securityContext:\n        privileged: false\n        readOnlyRootFilesystem: true\n        runAsUser: 1337\n    restartPolicy: Always\n    volumeMounts:\n    - mountPath: /etc/istio/proxy\n      name: istio-envoy\n    - mountPath: /etc/certs/\n      name: istio-certs\n      readOnly: true\n  volumes:\n  - emptyDir:\n      medium: Memory\n    name: istio-envoy\n  - name: istio-certs\n    secret:\n      optional: true\n      {{ if eq .Spec.ServiceAccountName \"\" -}}\n      secretName: istio.default\n      {{ else -}}\n      secretName: {{ printf \"istio.%s\" .Spec.ServiceAccountName }}\n      {{ end -}}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"istio-inject","namespace":"istio-system"}}
  creationTimestamp: 2018-02-09T10:10:44Z
  name: istio-inject
  namespace: istio-system
  resourceVersion: "125466"
  selfLink: /api/v1/namespaces/istio-system/configmaps/istio-inject
  uid: 7d67a765-0d81-11e8-8649-42010af00200
apiVersion: v1
data:
  config: |
    policy: disabled
    template: |-
      initContainers:
      - name: istio-init
        image: docker.io/istio/proxy_init:0.5.0
        args:
        - "-p"
        - {{ .MeshConfig.ProxyListenPort }}
        - "-u"
        - 1337
        - "-i"
        - 10.194.0.0/15,10.192.0.0/20
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        restartPolicy: Always
      containers:
      - name: istio-proxy
        image: docker.io/istio/proxy:0.5.0
        args:
        - proxy
        - sidecar
        - --configPath
        - {{ .ProxyConfig.ConfigPath }}
        - --binaryPath
        - {{ .ProxyConfig.BinaryPath }}
        - --serviceCluster
        {{ if ne "" (index .ObjectMeta.Labels "app") -}}
        - {{ index .ObjectMeta.Labels "app" }}
        {{ else -}}
        - "istio-proxy"
        {{ end -}}
        - --drainDuration
        - 2s
        - --parentShutdownDuration
        - 3s
        - --discoveryAddress
        - {{ .ProxyConfig.DiscoveryAddress }}
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - {{ .ProxyConfig.ZipkinAddress }}
        - --connectTimeout
        - 1s
        - --statsdUdpAddress
        - {{ .ProxyConfig.StatsdUdpAddress }}
        - --proxyAdminPort
        - {{ .ProxyConfig.ProxyAdminPort }}
        - --controlPlaneAuthPolicy
        - {{ .ProxyConfig.ControlPlaneAuthPolicy }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
        restartPolicy: Always
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          {{ if eq .Spec.ServiceAccountName "" -}}
          secretName: istio.default
          {{ else -}}
          secretName: {{ printf "istio.%s" .Spec.ServiceAccountName }}
          {{ end -}}
