apiVersion: v1
kind: Service
metadata:
  annotations:
    auth.istio.io/80: NONE
    auth.istio.io/443: NONE
  creationTimestamp: 2018-02-08T21:02:49Z
  labels:
    app: helm-infra-nginx-ingress
    chart: helm-infra-nginx-ingress-0.1.82
    heritage: Tiller
    release: helm-cmp-delivery-platform
  name: ingress-nginx-external
  namespace: ingress-nginx
  resourceVersion: "764408"
  selfLink: /api/v1/namespaces/ingress-nginx/services/ingress-nginx-external
  uid: 6b7ecb00-0d13-11e8-875e-42010af00222
spec:
  clusterIP: 10.192.14.206
  externalTrafficPolicy: Local
  healthCheckNodePort: 30019
  ports:
  - name: http-web
    nodePort: 30764
    port: 80
    protocol: TCP
    targetPort: http-web
  - name: https-web
    nodePort: 32073
    port: 443
    protocol: TCP
    targetPort: https-web
  selector:
    app: ingress-nginx-external
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.205.238.83
